# Generated by Django 3.2.2 on 2021-05-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('description', models.TextField(null=True, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип экрана')),
                ('diagonal', models.CharField(max_length=100, verbose_name='Диагональ экрана')),
                ('resolution_display', models.CharField(max_length=100, verbose_name='Разрешение экрана')),
                ('cpu_freq', models.CharField(max_length=100, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('sd_card', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=100, verbose_name='Встроенная память')),
                ('main_cam_mp', models.CharField(max_length=100, verbose_name='Основная камера')),
                ('front_cam_mp', models.CharField(max_length=100, verbose_name='Фронтальная камера')),
                ('battery_capacity', models.CharField(max_length=100, verbose_name='Емкость батареи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('description', models.TextField(null=True, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип экрана')),
                ('diagonal', models.CharField(max_length=100, verbose_name='Диагональ экрана')),
                ('cpu_freq', models.CharField(max_length=100, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('gpu', models.CharField(max_length=100, verbose_name='Используемый графический процессор')),
                ('battery_capacity', models.CharField(max_length=100, verbose_name='Емкость батареи')),
                ('time_without_charge', models.CharField(max_length=100, verbose_name='Время работы от батареи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
