# Generated by Django 3.2.2 on 2021-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210518_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='built_in_memory',
            field=models.CharField(default=256, max_length=100, verbose_name='Встроенная память'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_card',
            field=models.BooleanField(default=True, verbose_name='Поддержка карты памяти'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(max_length=100, verbose_name='Максимальный объем карты памяти'),
        ),
    ]
