# Generated by Django 3.2.2 on 2021-05-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210520_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальный объем карты памяти'),
        ),
    ]
